# Generated by Django 2.2 on 2019-05-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='category',
        ),
    ]
